version: "3.8"
services:
  officesupplies:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - SERVICE_NAME=officesupplies
    depends_on:
      - asdb
    ports: 
      - 7068:8080

  asdb:
    image: mariadb:latest
    ports:
      - "3312:3306"
    volumes:
      # - ./data/dump.sql:/docker-entrypoint-initdb.d/dump_latest.sql # populate db with data from dump
      - persistent-db-coffeetalk:/var/lib/mysql # persist local data in between runs
    environment:
      MYSQL_DATABASE: coffeetalk
      MYSQL_USER: coffeetalk
      MYSQL_PASSWORD: coffeetalk
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  persistent-db-coffeetalk:


