// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateUserList provides a mock function with given fields: c
func (_m *Repository) CreateUserList(c *gin.Context) {
	_m.Called(c)
}

// GetAllApprovedUserLists provides a mock function with given fields: c
func (_m *Repository) GetAllApprovedUserLists(c *gin.Context) {
	_m.Called(c)
}

// GetAllNotApprovedUserLists provides a mock function with given fields: c
func (_m *Repository) GetAllNotApprovedUserLists(c *gin.Context) {
	_m.Called(c)
}

// GetAllUserLists provides a mock function with given fields: c
func (_m *Repository) GetAllUserLists(c *gin.Context) {
	_m.Called(c)
}

// SendRemainderrest provides a mock function with given fields: c
func (_m *Repository) SendRemainderrest(c *gin.Context) {
	_m.Called(c)
}

// UpdateUserList provides a mock function with given fields: c
func (_m *Repository) UpdateUserList(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRepository(t mockConstructorTestingTNewRepository) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
